matrix:
  include:
    - os: osx
      osx_image: xcode8
      language: objective-c # so wrong
      before_install:
        - brew update
        - brew install rocksdb
      script: swift build -Xlinker -L/usr/local/lib && swift test -Xlinker -L/usr/local/lib
